/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    ExplorerContainer: typeof import('./src/components/ExplorerContainer.vue')['default']
    ExplorerContainerrr: typeof import('./src/components/ExplorerContainerrr.vue')['default']
    Fromalert: typeof import('./src/components/Fromalert.vue')['default']
    FromalertView: typeof import('./src/components/FromalertView.vue')['default']
    Frontalert: typeof import('./src/components/frontalert.vue')['default']
    IonAlert: typeof import('@ionic/vue')['IonAlert']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    KepalaView: typeof import('./src/components/KepalaView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
